#!/usr/bin/env python


import sys;
import binascii;
import array;
import csv, time, argparse;
import datetime
import os
from random import randrange
from GoodFETMCPCAN import GoodFETMCPCAN;
from intelhex import IntelHex;
from GoodFETMCPCANCommunication import *
from intelhex import IntelHex;


comm = GoodFETMCPCANCommunication()
freq = 500
verbose = True
#comm.sniff(freq=self.freq,duration=time,
#                  description=description,verbose=self.verbose,comment=comments,filename = None,
#                   standardid=standardid, debug = False)    
                   
                   
               
msgIDs, ids = comm.sweepRandom(freq = 500, time = 10, 100)